#include <random>
#include <iostream>
 
int main()
{
  int seed = 1;
  const int N = 10000;
  std::mt19937 gen(seed); //Standard mersenne_twister_engine seeded with rd()
  std::uniform_real_distribution<> dis(0.0, 1.0);
  for (int n = 0; n < N; ++n) {
    // Use dis to transform the random unsigned int generated by gen into a 
    // double in [0, 1). Each call to dis(gen) generates a new random double
    std::cout << dis(gen) << "\n";
  }
  std::cout << '\n';
}
